export type RegionMap = {
  [key: string]: string
}

export type RegionTranslations = {
  [key: string]: string
}

export const regionMap: RegionMap = {
  'Africa': '/img/continents/africa.svg',
  'North America': '/img/continents/americaNorte.svg',
  'South America': '/img/continents/southamerica.svg',
  'Asia': '/img/continents/asia.svg',
  'Europe': '/img/continents/europa.svg',
  'Oceania': '/img/continents/oceania.svg',
  'Antarctic': '/img/continents/antartida.png'
}

export const northAmericanCountries = [
  'USA', 'Canada', 'Mexico', 'Guatemala', 'Belize', 'El Salvador',
  'Honduras', 'Nicaragua', 'Costa Rica', 'Panama', 'Cuba', 'Jamaica',
  'Haiti', 'Dominican Republic', 'Bahamas', 'Puerto Rico', 'Greenland'
]

export const regionTranslations: RegionTranslations = {
  'Africa': 'África',
  'North America': 'América do Norte',
  'South America': 'América do Sul',
  'Asia': 'Ásia',
  'Europe': 'Europa',
  'Oceania': 'Oceania',
  'Antarctic': 'Antártida'
}

export const subregionTranslations: RegionTranslations = {
  'Northern Europe': 'Europa Setentrional',
  'Western Europe': 'Europa Ocidental',
  'Southern Europe': 'Europa Meridional',
  'Eastern Europe': 'Europa Oriental',
  'Northern Africa': 'África Setentrional',
  'Western Africa': 'África Ocidental',
  'Middle Africa': 'África Central',
  'Eastern Africa': 'África Oriental',
  'Southern Africa': 'África Meridional',
  'Central Asia': 'Ásia Central',
  'Eastern Asia': 'Ásia Oriental',
  'Southern Asia': 'Ásia Meridional',
  'South-Eastern Asia': 'Sudeste Asiático',
  'Western Asia': 'Ásia Ocidental',
  'Northern America': 'América Setentrional',
  'Central America': 'América Central',
  'South America': 'América do Sul',
  'Caribbean': 'Caribe',
  'Australia and New Zealand': 'Austrália e Nova Zelândia',
  'Melanesia': 'Melanésia',
  'Micronesia': 'Micronésia',
  'Polynesia': 'Polinésia'
}

export const languageTranslations: RegionTranslations = {
  'Afrikaans': 'Africâner',
  'Albanian': 'Albanês',
  'Amharic': 'Amárico',
  'Arabic': 'Árabe',
  'Armenian': 'Armênio',
  'Azerbaijani': 'Azerbaijano',
  'Basque': 'Basco',
  'Belarusian': 'Bielorrusso',
  'Bengali': 'Bengali',
  'Bosnian': 'Bósnio',
  'Bulgarian': 'Búlgaro',
  'Burmese': 'Birmanês',
  'Catalan': 'Catalão',
  'Chinese': 'Chinês',
  'Croatian': 'Croata',
  'Czech': 'Tcheco',
  'Danish': 'Dinamarquês',
  'Dutch': 'Holandês',
  'English': 'Inglês',
  'Estonian': 'Estoniano',
  'Filipino': 'Filipino',
  'Finnish': 'Finlandês',
  'French': 'Francês',
  'Galician': 'Galego',
  'Georgian': 'Georgiano',
  'German': 'Alemão',
  'Greek': 'Grego',
  'Gujarati': 'Guzerate',
  'Hausa': 'Hauçá',
  'Hebrew': 'Hebraico',
  'Hindi': 'Hindi',
  'Hungarian': 'Húngaro',
  'Icelandic': 'Islandês',
  'Indonesian': 'Indonésio',
  'Irish': 'Irlandês',
  'Italian': 'Italiano',
  'Japanese': 'Japonês',
  'Kannada': 'Canarês',
  'Kazakh': 'Cazaque',
  'Khmer': 'Khmer',
  'Korean': 'Coreano',
  'Kurdish': 'Curdo',
  'Kyrgyz': 'Quirguiz',
  'Lao': 'Laosiano',
  'Latin': 'Latim',
  'Latvian': 'Letão',
  'Lithuanian': 'Lituano',
  'Luxembourgish': 'Luxemburguês',
  'Macedonian': 'Macedônio',
  'Malagasy': 'Malgaxe',
  'Malay': 'Malaio',
  'Malayalam': 'Malaiala',
  'Maltese': 'Maltês',
  'Maori': 'Maori',
  'Marathi': 'Marata',
  'Mongolian': 'Mongol',
  'Nepali': 'Nepalês',
  'Norwegian': 'Norueguês',
  'Odia': 'Oriá',
  'Pashto': 'Pashto',
  'Persian': 'Persa',
  'Polish': 'Polonês',
  'Portuguese': 'Português',
  'Punjabi': 'Punjabi',
  'Romanian': 'Romeno',
  'Russian': 'Russo',
  'Samoan': 'Samoano',
  'Scottish Gaelic': 'Gaélico Escocês',
  'Serbian': 'Sérvio',
  'Shona': 'Shona',
  'Sindhi': 'Sindi',
  'Sinhala': 'Cingalês',
  'Slovak': 'Eslovaco',
  'Slovenian': 'Esloveno',
  'Somali': 'Somali',
  'Spanish': 'Espanhol',
  'Sundanese': 'Sundanês',
  'Swahili': 'Suaíli',
  'Swedish': 'Sueco',
  'Tajik': 'Tajique',
  'Tamil': 'Tâmil',
  'Telugu': 'Télugo',
  'Thai': 'Tailandês',
  'Turkish': 'Turco',
  'Ukrainian': 'Ucraniano',
  'Urdu': 'Urdu',
  'Uzbek': 'Uzbeque',
  'Vietnamese': 'Vietnamita',
  'Welsh': 'Galês',
  'Xhosa': 'Xhosa',
  'Yiddish': 'Iídiche',
  'Yoruba': 'Iorubá',
  'Zulu': 'Zulu'
}

export const officialNameTranslations: RegionTranslations = {
  'Republic of the Congo': 'República do Congo',
  'Democratic Republic of the Congo': 'República Democrática do Congo',
  'United States of America': 'Estados Unidos da América',
  'United Kingdom of Great Britain and Northern Ireland': 'Reino Unido da Grã-Bretanha e Irlanda do Norte',
  'Russian Federation': 'Federação Russa',
  'People\'s Republic of China': 'República Popular da China',
  'Republic of India': 'República da Índia',
  'Federal Republic of Germany': 'República Federal da Alemanha',
  'French Republic': 'República Francesa',
  'Italian Republic': 'República Italiana',
  'Kingdom of Spain': 'Reino da Espanha',
  'Portuguese Republic': 'República Portuguesa',
  'Kingdom of the Netherlands': 'Reino dos Países Baixos',
  'Kingdom of Belgium': 'Reino da Bélgica',
  'Swiss Confederation': 'Confederação Suíça',
  'Republic of Austria': 'República da Áustria',
  'Kingdom of Sweden': 'Reino da Suécia',
  'Kingdom of Norway': 'Reino da Noruega',
  'Kingdom of Denmark': 'Reino da Dinamarca',
  'Republic of Finland': 'República da Finlândia',
  'Republic of Poland': 'República da Polônia',
  'Czech Republic': 'República Tcheca',
  'Slovak Republic': 'República Eslovaca',
  'Republic of Hungary': 'República da Hungria',
  'Republic of Croatia': 'República da Croácia',
  'Republic of Serbia': 'República da Sérvia',
  'Republic of Bulgaria': 'República da Bulgária',
  'Hellenic Republic': 'República Helênica',
  'Republic of Turkey': 'República da Turquia',
  'State of Israel': 'Estado de Israel',
  'Kingdom of Saudi Arabia': 'Reino da Arábia Saudita',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'Islamic Republic of Iran': 'República Islâmica do Irã',
  'Republic of Iraq': 'República do Iraque',
  'Syrian Arab Republic': 'República Árabe Síria',
  'Republic of Lebanon': 'República do Líbano',
  'Hashemite Kingdom of Jordan': 'Reino Hachemita da Jordânia',
  'State of Palestine': 'Estado da Palestina',
  'Arab Republic of Egypt': 'República Árabe do Egito',
  'Republic of the Sudan': 'República do Sudão',
  'Federal Democratic Republic of Ethiopia': 'República Democrática Federal da Etiópia',
  'Republic of Kenya': 'República do Quênia',
  'United Republic of Tanzania': 'República Unida da Tanzânia',
  'Republic of Uganda': 'República de Uganda',
  'Republic of Rwanda': 'República de Ruanda',
  'Republic of Burundi': 'República do Burundi',
  'Democratic Republic of Timor-Leste': 'República Democrática de Timor-Leste',
  'Republic of Indonesia': 'República da Indonésia',
  'Republic of the Philippines': 'República das Filipinas',
  'Kingdom of Thailand': 'Reino da Tailândia',
  'Socialist Republic of Vietnam': 'República Socialista do Vietnã',
  'Kingdom of Cambodia': 'Reino do Camboja',
  'Lao People\'s Democratic Republic': 'República Democrática Popular do Laos',
  'Republic of the Union of Myanmar': 'República da União de Mianmar',
  'People\'s Republic of Bangladesh': 'República Popular de Bangladesh',
  'Federal Democratic Republic of Nepal': 'República Democrática Federal do Nepal',
  'Republic of Maldives': 'República das Maldivas',
  'Democratic Socialist Republic of Sri Lanka': 'República Democrática Socialista do Sri Lanka',
  'Islamic Republic of Pakistan': 'República Islâmica do Paquistão',
  'Republic of Kazakhstan': 'República do Cazaquistão',
  'Kyrgyz Republic': 'República do Quirguistão',
  'Republic of Tajikistan': 'República do Tajiquistão',
  'Republic of Uzbekistan': 'República do Uzbequistão',
  'Republic of Azerbaijan': 'República do Azerbaijão',
  'Republic of Armenia': 'República da Armênia',
  'Republic of Georgia': 'República da Geórgia',
  'Republic of Moldova': 'República da Moldávia',
  'Republic of Belarus': 'República da Bielorrússia',
  'Republic of Lithuania': 'República da Lituânia',
  'Republic of Latvia': 'República da Letônia',
  'Republic of Estonia': 'República da Estônia',
  'Republic of Iceland': 'República da Islândia',
  'Kingdom of Morocco': 'Reino de Marrocos',
  'People\'s Democratic Republic of Algeria': 'República Democrática Popular da Argélia',
  'Republic of Tunisia': 'República da Tunísia',
  'State of Libya': 'Estado da Líbia',
  'Republic of Mali': 'República do Mali',
  'Republic of Niger': 'República do Níger',
  'Burkina Faso': 'Burkina Faso',
  'Republic of Senegal': 'República do Senegal',
  'Republic of Guinea': 'República da Guiné',
  'Republic of Guinea-Bissau': 'República da Guiné-Bissau',
  'Republic of Sierra Leone': 'República de Serra Leoa',
  'Republic of Liberia': 'República da Libéria',
  'Republic of Côte d\'Ivoire': 'República da Costa do Marfim',
  'Republic of Ghana': 'República de Gana',
  'Republic of Togo': 'República do Togo',
  'Republic of Benin': 'República do Benim',
  'Federal Republic of Nigeria': 'República Federal da Nigéria',
  'Republic of Cameroon': 'República dos Camarões',
  'Central African Republic': 'República Centro-Africana',
  'Republic of Chad': 'República do Chade',
  'Republic of South Sudan': 'República do Sudão do Sul',
  'Republic of Djibouti': 'República do Djibuti',
  'Republic of Eritrea': 'República da Eritreia',
  'Republic of Somalia': 'República da Somália',
  'Republic of Angola': 'República de Angola',
  'Republic of Zambia': 'República da Zâmbia',
  'Republic of Malawi': 'República do Malawi',
  'Republic of Mozambique': 'República de Moçambique',
  'Republic of Zimbabwe': 'República do Zimbábue',
  'Republic of Botswana': 'República de Botsuana',
  'Kingdom of Eswatini': 'Reino de Essuatíni',
  'Kingdom of Lesotho': 'Reino do Lesoto',
  'Republic of Namibia': 'República da Namíbia',
  'Republic of South Africa': 'República da África do Sul',
  'Republic of Madagascar': 'República de Madagascar',
  'Union of the Comoros': 'União das Comores',
  'Republic of Seychelles': 'República das Seicheles',
  'Republic of Mauritius': 'República de Maurício',
  'Republic of Cape Verde': 'República de Cabo Verde',
  'Republic of São Tomé and Príncipe': 'República de São Tomé e Príncipe',
  'Republic of Equatorial Guinea': 'República da Guiné Equatorial',
  'Gabonese Republic': 'República Gabonesa',
  'Kingdom of Bhutan': 'Reino do Butão',
  'Republic of China': 'República da China',
  'Democratic People\'s Republic of Korea': 'República Popular Democrática da Coreia',
  'Republic of Korea': 'República da Coreia',
  'State of Japan': 'Estado do Japão',
  'Mongolia': 'Mongólia',
  'Republic of Turkmenistan': 'República do Turcomenistão',
  'Islamic Republic of Afghanistan': 'República Islâmica do Afeganistão',
  'State of Kuwait': 'Estado do Kuwait',
  'State of Qatar': 'Estado do Catar',
  'Sultanate of Oman': 'Sultanato de Omã',
  'Republic of Yemen': 'República do Iêmen',
  'Republic of Cyprus': 'República de Chipre',
  'Republic of Malta': 'República de Malta',
  'Republic of San Marino': 'República de San Marino',
  'Vatican City State': 'Estado da Cidade do Vaticano',
  'Republic of Slovenia': 'República da Eslovênia',
  'Ukraine': 'Ucrânia',
  'Republic of Albania': 'República da Albânia',
  'Republic of North Macedonia': 'República da Macedônia do Norte',
  'Montenegro': 'Montenegro',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Republic of Kosovo': 'República do Kosovo',
  'Principality of Liechtenstein': 'Principado de Liechtenstein',
  'Grand Duchy of Luxembourg': 'Grão-Ducado de Luxemburgo',
  'Principality of Monaco': 'Principado de Mônaco',
  'Republic of Ireland': 'República da Irlanda',
  'Commonwealth of Australia': 'Comunidade da Austrália',
  'New Zealand': 'Nova Zelândia',
  'Independent State of Papua New Guinea': 'Estado Independente de Papua-Nova Guiné',
  'Republic of Fiji': 'República de Fiji',
  'Republic of Vanuatu': 'República de Vanuatu',
  'Solomon Islands': 'Ilhas Salomão',
  'Independent State of Samoa': 'Estado Independente de Samoa',
  'Kingdom of Tonga': 'Reino de Tonga',
  'Tuvalu': 'Tuvalu',
  'Republic of Kiribati': 'República de Kiribati',
  'Republic of the Marshall Islands': 'República das Ilhas Marshall',
  'Republic of Nauru': 'República de Nauru',
  'Republic of Palau': 'República de Palau',
  'Federated States of Micronesia': 'Estados Federados da Micronésia',
  'Commonwealth of the Northern Mariana Islands': 'Comunidade das Ilhas Marianas do Norte',
  'Territory of Guam': 'Território de Guam',
  'Territory of American Samoa': 'Território da Samoa Americana',
  'Territory of the Wallis and Futuna Islands': 'Território das Ilhas Wallis e Futuna',
  'Territory of French Polynesia': 'Território da Polinésia Francesa',
  'Territory of New Caledonia': 'Território da Nova Caledônia',
  'Territory of Norfolk Island': 'Território da Ilha Norfolk',
  'Territory of the Cocos (Keeling) Islands': 'Território das Ilhas Cocos (Keeling)',
  'Territory of Christmas Island': 'Território da Ilha do Natal',
  'Territory of the Pitcairn Islands': 'Território das Ilhas Pitcairn',
  'Territory of Tokelau': 'Território de Tokelau',
  'Territory of Niue': 'Território de Niue',
  'Territory of the Cook Islands': 'Território das Ilhas Cook',
  'Territory of French Southern and Antarctic Lands': 'Território das Terras Austrais e Antárticas Francesas',
  'Territory of Heard Island and McDonald Islands': 'Território da Ilha Heard e Ilhas McDonald',
  'Territory of the British Indian Ocean Territory': 'Território Britânico do Oceano Índico',
  'Territory of the Falkland Islands': 'Território das Ilhas Malvinas',
  'Territory of South Georgia and the South Sandwich Islands': 'Território da Geórgia do Sul e Ilhas Sandwich do Sul',
  'Territory of Bouvet Island': 'Território da Ilha Bouvet',
  'Territory of Jan Mayen': 'Território de Jan Mayen',
  'Territory of Svalbard': 'Território de Svalbard',
  'Territory of the Faroe Islands': 'Território das Ilhas Faroé',
  'Territory of Åland Islands': 'Território das Ilhas Åland',
  'Territory of Gibraltar': 'Território de Gibraltar',
  'Territory of the Isle of Man': 'Território da Ilha de Man',
  'Territory of the Channel Islands': 'Território das Ilhas do Canal',
  'Territory of the British Virgin Islands': 'Território das Ilhas Virgens Britânicas',
  'Territory of the Cayman Islands': 'Território das Ilhas Cayman',
  'Territory of the Turks and Caicos Islands': 'Território das Ilhas Turcas e Caicos',
  'Territory of Anguilla': 'Território de Anguilla',
  'Territory of Montserrat': 'Território de Montserrat',
  'Territory of Bermuda': 'Território das Bermudas',
  'Territory of Saint Helena, Ascension and Tristan da Cunha': 'Território de Santa Helena, Ascensão e Tristão da Cunha',
  'Territory of Puerto Rico': 'Território de Porto Rico',
  'Territory of the United States Virgin Islands': 'Território das Ilhas Virgens Americanas'
}
